services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.production
    ports:
      - "${WEB_PORT:-3012}:3012"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    ports:
      - "${API_PORT:-3102}:3102"
    restart: unless-stopped
    networks:
      - workplan-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  workplan-network:
    driver: bridge
